config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callback"}
  resources :statuses

  root 'statuses#index'

end

app/models/status.rb
class Status < ActiveRecord::Base
	attr_accessible :contenido, :user_id
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :primer_nombre, :primer_apellido, :nombre_perfil,
            :email, :password, :password_confirmation, :provider, :uid
  
  has_many :statuses

  def nombre_completo
    primer_nombre + " " + primer_apellido           
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(primer_nombre: auth.extra.raw_info.first_name, primer_apellido: auth.extra.raw_info.last_name,
         nombre_perfil: auth.info.nickname, provider: auth.provider,
                    uid: auth.uid, email: auth.info.email, password: Devise.friendly_token[0,20]
        )
      end
    end
  end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:primer_nombre, :primer_apellido, :nombre_perfil, :email, :password, :password_confirmation, :provider, :uid) }
  end

  
end

app/controllers/omniauth_callback_controller.rb
class OmniauthCallbackController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      flash[:notice] ="OK"
      if is_navigational_format?

      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    @status.save
    respond_with(@status)
  end

  def update
    @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:user_id, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callback_helper.rb
module OmniauthCallbackHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loginfb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a href="#" class="navbar-brand logo">Footbook</a>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Status", statuses_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.primer_nombre, edit_user_registration_path %></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "iniciar sesión", new_user_session_path %></li>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
            <li><%= link_to "Inciar con facebook", user_omniauth_authorize_path(:facebook)%></li>
          <% end %>
        </ul>
      </div>
  </nav>
<div class="container">
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<%= yield %>

</div>
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :user_id, collection: User.last, label_method: :nombre_completo %>
    <%= f.input :contenido %>
    <%= f.button :submit, 'Crear estado' %>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Todos los estados</h1>
</div>

<%= link_to "Nuevo post", new_status_path, class: "btn btn-primary" %>

<% @statuses.each do |status| %>
  <br>
  <div class="status">
    <strong><%= status.user.nombre_completo %></strong>
    <p><%= status.contenido %></p>
    <div>
      <%= link_to "Hace "+ time_ago_in_words(status.created_at), status %> |
      <span class="admin">
        <%= link_to "Editar", edit_status_path(status) %> |
        <%= link_to "Borrar", status, method: :delete, data: {confirm: "¿Estas seguro de borrar este estado?"} %>
      </span>
    </div>
  </div>

<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @status.user.nombre_completo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @status.contenido %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>